#include "fortunes.hpp"

#include <string>

const std::string fortunes[FORTUNES] = {
"\"Welcome\" is a powerful word.",
"A dubious friend may be an enemy in camouflage.",
"A feather in the hand is better than a bird in the air.",
"A fresh start will put you on your way.",
"A friend asks only for your time not your money.",
"A friend is a present you give yourself.",
"A gambler not only will lose what he has, but also will lose what he doesn't have.",
"A golden egg of opportunity falls into your lap this month.",
"A good time to finish up old tasks.",
"A hunch is creativity trying to tell you something.",
"A light heart carries you through all the hard times.",
"A new perspective will come with the new year.",
"A person is never too old to learn.",
"A person of words and not deeds is like a garden full of weeds.",
"A pleasant surprise is waiting for you.",
"A smile is your personal welcome mat.",
"A smooth long journey! Great expectations.",
"A soft voice may be awfully persuasive.",
"A truly rich life contains love and art in abundance.",
"Accept something that you cannot change, and you will feel better.",
"Adventure can be real happiness.",
"Advice is like kissing. It costs nothing and is a pleasant thing to do.",
"Advice, when most needed, is least heeded.",
"All the effort you are making will ultimately pay off.",
"All the troubles you have will pass away very quickly.",
"All will go well with your new project.",
"All your hard work will soon pay off.",
"Allow compassion to guide your decisions.",
"An agreeable romance might begin to take on the appearance.",
"An important person will offer you support.",
"An inch of time is an inch of gold.",
"Be careful or you could fall for some tricks today.",
"Beauty in its various forms appeals to you.",
"Because you demand more from yourself, others respect you deeply.",
"Believe in yourself and others will too.",
"Believe it can be done.",
"Better ask twice than lose yourself once.",
"Carve your name on your heart and not on marble.",
"Change is happening in your life, so go with the flow!",
"Competence like yours is underrated.",
"Congratulations! You are on your way.",
"Could I get some directions to your heart?",
"Courtesy begins in the home.",
"Courtesy is contagious.",
"Curiosity kills boredom. Nothing can kill curiosity.",
"Dedicate yourself with a calm mind to the task at hand.",
"Depart not from the path which fate has you assigned.",
"Determination is what you need now.",
"Disbelief destroys the magic.",
"Distance yourself from the vain.",
"Do not be intimidated by the eloquence of others.",
"Do not let ambitions overshadow small success.",
"Do not make extra work for yourself.",
"Do not underestimate yourself. Human beings have unlimited potentials.",
"Don't be discouraged, because every wrong attempt discarded is another step forward.",
"Don't confuse recklessness with confidence.",
"Don't just spend time. Invest it.",
"Don't just think, act!",
"Don't let friends impose on you, work calmly and silently.",
"Don't let the past and useless detail choke your existence.",
"Don't let your limitations overshadow your talents.",
"Don't worry; prosperity will knock on your door soon.",
"Each day, compel yourself to do something you would rather not do.",
"Education is the ability to meet life's situations.",
"Emulate what you admire in your parents.",
"Emulate what you respect in your friends.",
"Every flower blooms in its own sweet time.",
"Every wise man started out by asking many questions.",
"Everyday in your life is a special occasion.",
"Failure is the chance to do better next time.",
"Feeding a cow with roses does not get extra appreciation.",
"For hate is never conquered by hate. Hate is conquered by love.",
"Fortune Not Found: Abort, Retry, Ignore?"
"From listening comes wisdom and from speaking repentance.",
"From now on your kindness will lead you to success.",
"Get your mind set... confidence will lead you on.",
"Go take a rest; you deserve it.",
"Good news will be brought to you by mail.",
"Good news will come to you by mail.",
"Good to begin well, better to end well.",
"Happiness begins with facing life with a smile and a wink.",
"Happiness will bring you good luck.",
"Happy life is just in front of you.",
"Hard words break no bones, fine words butter no parsnips.",
"Have a beautiful day.",
"He who expects no gratitude shall never be disappointed.",
"He who knows he has enough is rich.",
"Help! I'm being held prisoner in a chinese bakery!",
"How you look depends on where you go.",
"I learn by going where I have to go.",
"If a true sense of value is to be yours it must come through service.",
"If certainty were truth, we would never be wrong.",
"If you continually give, you will continually have.",
"If you look in the right places, you can find some good offerings.",
"If you think you can do a thing or think you can't do a thing, you're right.",
"If your desires are not extravagant, they will be granted.",
"If your desires are not to extravagant they will be granted.",
"In order to take, one must first give.",
"In the end all things will be known.",
"It could be better, but it's good enough.",
"It is better to deal with problems before they arise.",
"It is honorable to stand up for what is right, however unpopular it seems.",
"It is worth reviewing some old lessons.",
"It takes courage to admit fault.",
"It's time to get moving. Your spirits will lift accordingly.",
"Keep your face to the sunshine and you will never see shadows.",
"Let the world be filled with tranquility and goodwill.",
"Listen not to vain words of empty tongue.",
"Listen to everyone. Ideas come from everywhere.",
"Living with a commitment to excellence shall take you far.",
"Long life is in store for you.",
"Love is a warm fire to keep the soul warm.",
"Love is like sweet medicine, good to the last drop.",
"Love lights up the world.",
"Love truth, but pardon error.",
"Man is born to live and not prepared to live.",
"Many will travel to hear you speak.",
"Meditation with an old enemy is advised.",
"Miles are covered one step at a time.",
"Nature, time and patience are the three great physicians.",
"Never fear! The end of something marks the start of something new.",
"New ideas could be profitable.",
"New people will bring you new realizations, especially about big issues.",
"No one can walk backwards into the future.",
"Now is a good time to buy stock.",
"Now is the time to go ahead and pursue that love interest!",
"Now is the time to try something new.",
"Others can help you now.",
"Pennies from heaven find their way to your doorstep this year!",
"People are attracted by your Delicate features.",
"People find it difficult to resist your persuasive manner.",
"Perhaps you've been focusing too much on saving.",
"Physical activity will dramatically improve your outlook today.",
"Place special emphasis on old friendship.",
"Practice makes perfect.",
"Protective measures will prevent costly disasters.",
"Put your mind into planning today. Look into the future.",
"Remember to share good fortune as well as bad with your friends.",
"Rest has a peaceful effect on your physical and emotional health.",
"Resting well is as important as working hard.",
"Romance moves you in a new direction.",
"Savor your freedom -- it is precious.",
"Say hello to others. You will have a happier day.",
"Self-knowledge is a life long process.",
"Share your joys and sorrows with your family.",
"Sloth makes all things difficult; industry all easy.",
"Small confidences mark the onset of a friendship.",
"Society prepares the crime; the criminal commits it.",
"Someone you care about seeks reconciliation.",
"Soon life will become more interesting.",
"Stand tall! Don't look down upon yourself.",
"Stop searching forever, happiness is just next to you.",
"Success is a journey, not a destination.",
"Success is going from failure to failure without loss of enthusiasm.",
"Take care and sensitivity you show towards others will return to you.",
"Take the high road.",
"The austerity you see around you covers the richness of life like a veil.",
"The best prediction of future is the past.",
"The change you started already have far-reaching effects. Be ready.",
"The first man gets the oyster, the second man gets the shell.",
"The harder you work, the luckier you get.",
"The night life is for you.",
"The one that recognizes the illusion does not act as if it is real.",
"The only people who never fail are those who never try.",
"The person who will not stand for something will fall for anything.",
"The philosophy of one century is the common sense of the next.",
"The saints are the sinners who keep on trying.",
"The secret to good friends is no secret to you.",
"The small courtesies sweeten life, the greater ennoble it.",
"The smart thing to do is to begin trusting your intuitions.",
"The strong person understands how to withstand substantial loss.",
"The sure way to predict the future is to invent it.",
"The truly generous share, even with the undeserving.",
"The value lies not within any particular thing, but in the desire placed on that thing.",
"The weather is wonderful.",
"There is no mistake so great as that of being always right.",
"There is no wisdom greater than kindness.",
"There is not greater pleasure than seeing your loved ones prosper.",
"There's no such thing as an ordinary cat.",
"Things don't just happen; they happen just.",
"Those who care will make the effort.",
"Time and patience are called for many surprises await you!.",
"Time is precious, but truth is more precious than time.",
"To know oneself, one should assert oneself.",
"Today is the conserve yourself, as things just won't budge.",
"Today, your mouth might be moving but no one is listening.",
"Tonight you will be blinded by passion.",
"Use your eloquence where it will do the most good.",
"Welcome change.",
"Well done is better than well said.",
"What's hidden in an empty box?",
"What's yours is mine, and what's mine is mine.",
"When your heart is pure, your mind is clear.",
"Wish you happiness.",
"You always bring others happiness.",
"You are a person of another time.",
"You are a talented storyteller.",
"You are admired by everyone for your talent and ability.",
"You are almost there.",
"You are busy, but you are happy.",
"You are generous to an extreme and always think of the other fellow.",
"You are going to have some new clothes.",
"You are in good hands this evening.",
"You are modest and courteous.",
"You are never selfish with your advice or your help.",
"You are next in line for promotion in your firm.",
"You are offered the dream of a lifetime. Say yes!",
"You are open-minded and quick to make new friends.",
"You are solid and dependable.",
"You are soon going to change your present line of work.",
"You are talented in many ways.",
"You are the master of every situation.",
"You are very expressive and positive in words, act and feeling.",
"You are working hard.",
"You begin to appreciate how important it is to share your personal beliefs.",
"You desire recognition and you will find it.",
"You have a deep appreciation of the arts and music.",
"You have a deep interest in all that is artistic.",
"You have a friendly heart and are well admired.",
"You have a shrewd knack for spotting insincerity.",
"You have a yearning for perfection.",
"You have an active mind and a keen imagination.",
"You have an ambitious nature and may make a name for yourself.",
"You have an unusual equipment for success, use it properly.",
"You have exceeded what was expected.",
"You have the power to write your own fortune.",
"You have yearning for perfection.",
"You know where you are going and how to get there.",
"You look pretty.",
"You love challenge.",
"You make people realize that there exist other beauties in the world.",
"You never hesitate to tackle the most difficult problems.",
"You seek to shield those you love and like the role of provider.",
"You should be able to make money and hold on to it.",
"You should be able to undertake and complete anything.",
"You understand how to have fun with others and to enjoy your solitude.",
"You will always be surrounded by true friends.",
"You will always get what you want through your charm and personality.",
"You will always have good luck in your personal affairs.",
"You will be a great success both in the business world and society.",
"You will be blessed with longevity.",
"You will be successful in your work.",
"You will be traveling and coming into a fortune.",
"You will be unusually successful in business.",
"You will become a great philanthropist in your later years.",
"You will become more and more wealthy.",
"You will enjoy good health.",
"You will enjoy good health; you will be surrounded by luxury.",
"You will find great contentment in the daily, routine activities.",
"You will have a fine capacity for the enjoyment of life.",
"You will have gold pieces by the bushel.",
"You will inherit a large sum of money.",
"You will make change for the better.",
"You will soon be surrounded by good friends and laughter.",
"You will take a chance in something in near future.",
"You will travel far and wide, both pleasure and business.",
"You will travel far and wide,both pleasure and business.",
"Your abilities are unparalleled.",
"Your ability is appreciated.",
"Your ability to juggle many tasks will take you far.",
"Your biggest virtue is your modesty.",
"Your character can be described as natural and unrestrained.",
"Your difficulties will strengthen you.",
"Your dreams are never silly; depend on them to guide you.",
"Your dreams are worth your best efforts to achieve them.",
"Your energy returns and you get things done.",
"Your family is young, gifted and attractive.",
"Your first love has never forgotten you.",
"Your happiness is before you, not behind you! Cherish it.",
"Your hard work will payoff today.",
"Your heart will always make itself known through your words.",
"Your home is the center of great love.",
"Your ideals are well within your reach.",
"Your infinite capacity for patience will be rewarded sooner or later.",
"Your leadership qualities will be tested and proven.",
"Your life will be happy and peaceful.",
"Your life will get more and more exciting.",
"Your love life will be happy and harmonious.",
"Your love of music will be an important part of your life.",
"Your loyalty is a virtue, but not when it's wedded with blind subbornness.",
"Your mind is creative, original and alert.",
"Your mind is your greatest asset.",
"Your quick wits will get you out of a tough situation.",
"Your success will astonish everyone.",
"Your talents will be recognized and suitably rewarded.",
"Your work interests can capture the highest status or prestige.",
};

const std::string quotes[QUOTES] = {
"A celebrity is a person who works hard all his life to become well known,\n then wears dark glasses to avoid being recognized.  ~Fred Allen",
"A compromise is an agreement whereby both parties get what neither of them wanted.  ~Author Unknown",
"A conclusion is the place where you got tired of thinking.  ~Attributed to Arthur McBride Bloch",
"A gentleman is a man who can play the accordion but doesn't.  ~Author Unknown",
"Don't worry about the world coming to an end today.\nIt is already tomorrow in Australia.  ~Charles Schulz",
"All generalizations are bad.  ~R.H. Grenier",
"All my life, I always wanted to be somebody.\nNow I see that I should have been more specific.\n~Jane Wagner",
"The large print giveth, but the small print taketh away.  ~Tom Waits, Small Change",
"Eagles may soar in the clouds,\n but weasels never get sucked into jet engines.  ~Attributed to both Jason Hutchison and John Benfield",
"After all, what is your host's purpose in having a party?\nSurely not for you to enjoy yourself.\nIf that were their sole purpose,\n they'd have simply sent champagne and women over to your place by taxi.  ~P.J. O'Rourke",
"How come there's only one Monopolies Commission?  ~Nigel Rees",
"I have six locks on my door all in a row.\nWhen I go out, I lock every other one.\nI figure no matter how long somebody stands there picking the locks,\n they are always locking three.  ~Elayne Boosler",
"Anybody can win, unless there happens to be a second entry.  ~George Ade",
"An expert is a man who tells you a simple thing in a confused way in such a fashion\n as to make you think the confusion is your own fault.  ~William Castle",
"If The Phone Doesn't Ring, It's Me.  ~Song title by Jimmy Buffet",
"Man was predestined to have free will.  ~Hal Lee Luyah",
"Maybe this world is another planet's hell.  ~Aldous Huxley",
"Murphy was an optimist.  ~O'Toole's Commentary",
"The remarkable thing about Shakespeare is that he really is very good,\n in spite of all the people who say he is very good.  ~Robert Graves",
"The ships hung in the sky in much the same way that bricks don't.  ~Douglas Adams",
"The surest sign that intelligent life exists elsewhere in the universe is\n that it has never tried to contact us.  ~Bill Watterson, Calvin and Hobbes",
"Today is the last day of some of your life.  ~Author Unknown",
"Without geography, you're nowhere.  ~Author Unknown",
"It's always darkest before the dawn.\nSo if you're going to steal your neighbor's newspaper,\nthat's the time to do it.  ~Author Unknown",
"You can't have everything... where would you put it?  ~Steven Wright",
"He's turned his life around.\nHe used to be depressed and miserable.\nNow he's miserable and depressed.\n~Harry Kalas, on Garry Maddox, 1981",
"He who believes that the past cannot be changed has not yet written his memoirs. ~Torvald Gahlin",
"I plan on living forever.  So far, so good. ~Author Unknown",
"Ability is what will get you to the top if the boss has no daughter.  ~Author Unknown",
"Love your enemies.  It makes them so damned mad.  ~P.D. East",
"I usually lump organized religion, organized labor, and organized crime together.\nThe Mafia gets points for having the best restaurants.  ~Dave Beard",
"There's no such thing as fun for the whole family.  ~Jerry Seinfeld",
"My doctor says that I have a malformed public-duty gland\n and a natural deficiency in moral fiber,\n and that I am therefore excused from saving Universes.  ~Douglas Adams",
"When somebody tells you nothing is impossible, ask him to dribble a football.  ~Author Unknown",
"The chicken came first - God would look silly sitting on an egg.  ~Author Unknown",
"The early bird gets the worm, but the second mouse gets the cheese.  ~Author Unknown",
"A great name for a new country song:  If I'd Shot You Sooner, I'd Be Out of Jail by Now.  ~Author Unknown",
"Lead me not into temptation; I can find the way myself.  ~Rita Mae Brown",
"A prisoner of war is a man who tries to kill you and fails, and then asks you not to kill him.  ~Sir Winston Churchill",
"Just remember, if the world didn't suck, we'd all fall off.  ~Author Unknown",
"Before you criticize someone, you should walk a mile in their shoes.\nThat way, when you criticize them,\n you're a mile way and you have their shoes.  ~Author Unknown",
"How do the angels get to sleep when the devil leaves the porch light on?  ~Tom Waits,  Heartattack and Vine",
"Duct tape is like the force.  It has a light side, a dark side, and it holds the universe together.  ~Carl Zwanzig",
"A signature always reveals a man's character - and sometimes even his name.  ~Evan Esar",
"Can we actually \"know\" the universe?\nMy God, it's hard enough finding your way around in Chinatown.  ~Woody Allen, Getting Even, 1971",
"A scout troop consists of twelve little kids dressed like schmucks\n following a big schmuck dressed like a kid.  ~Jack Benny",
"I learned law so well, the day I graduated I sued the college,\n won the case, and got my tuition back.  ~Fred Allen",
"Resolve is never stronger than in the morning after the night it was never weaker.  ~From the movie Naked",
"Just because you're not paranoid doesn't mean they're not out to get you.  ~Colin Sautar",
"Who says nothing is impossible.  I've been doing nothing for years.  ~Author Unknown",
"I used to eat a lot of natural foods until I learned that most people die of natural causes.  ~Author Unknown",
"She's the kind of girl who climbed the ladder of success wrong by wrong.  ~Mae West",
"If you cannot answer a man's argument, all it not lost.\nYou can still call him vile names.  ~Elbert Hubbard",
"If Barbie is so popular, why do you have to buy her friends?  ~Author Unknown",
"She was what we used to call a suicide blond - dyed by her own hand.  ~Saul Bellow",
"It used to take me all vacation to grow a new hide in place of the one they flogged off me during school term.  ~Mark Twain",
"Protect me from knowing what I don't need to know.\nProtect me from even knowing that there are things to know that I don't know.\nProtect me from knowing that I decided not to know about the things that I decided not to know about.\nAmen.~Douglas Adams, Mostly Harmless",
"May those who love us love us,\n and those who do not love us,\n may God turn their hearts,\n and if He cannot turn their hearts\n may He turn their ankles\n that we may know them by their limping.\n ~Irish Prayer",
 "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs,\n and the universe trying to build bigger and better idiots. So far, the universe is winning.\n - Rick Cook",
 "Lisp isn't a language, it's a building material. - Alan Kay.",
 "Walking on water and developing software from a specification are easy if both are frozen. - Edward V Berard",
 "They don't make bugs like Bunny anymore. - Olav Mjelde.",
 "A programming language is low level when its programs require attention to the irrelevant. - Alan J. Perlis.",
 "A C program is like a fast dance on a newly waxed dance floor by people carrying razors. - Waldi Ravens.",
 "I have always wished for my computer to be as easy to use as my telephone;\n my wish has come true because I can no longer figure out how to use my telephone. - Bjarne Stroustrup",
 "Computer science education cannot make anybody an expert programmer any more than studying brushes\n and pigment can make somebody an expert painter. - Eric S. Raymond",
 "Don't worry if it doesn't work right. If everything did, you'd be out of a job.\n - Mosher's Law of Software Engineering",
 "I think Microsoft named .Net so it wouldn't show up in a Unix directory listing. - Oktal",
 "Fine, Java MIGHT be a good example of what a programming language should be like.\n But Java applications are good examples of what applications SHOULDN'T be like. - pixadel",
 "The use of COBOL cripples the mind; its teaching should therefore be regarded as a criminal offense.\n - E.W. Dijkstra",
 "In the one and only true way. The object-oriented version of 'Spaghetti code' is,\n of course, 'Lasagna code'. (Too many layers). - Roberto Waltman.",
 "FORTRAN is not a flower but a weed --\n it is hardy, occasionally blooms, and grows in every computer. - Alan J. Perlis.",
 "For a long time it puzzled me how something so expensive, so leading edge, could be so useless.\n And then it occurred to me that a computer is a stupid machine with the ability to do incredibly smart things,\n while computer programmers are smart people with the ability to do incredibly stupid things.\n They are, in short, a perfect match. - Bill Bryson",
 "In My Egotistical Opinion, most people's C programs should be indented six feet downward and covered with dirt.\n - Blair P. Houghton.",
 "When someone says: 'I want a programming language in which I need only say what I wish done',\n give him a lollipop. - Alan J. Perlis",
 "Good design adds value faster than it adds cost. - Thomas C. Gale",
 "Python's a drop-in replacement for BASIC in the sense that Optimus Prime is a drop-in replacement for a truck.\n - Cory Dodt",
 "Talk is cheap. Show me the code. - Linus Torvalds",
 "Perfection [in design] is achieved, not when there is nothing more to add, but when there is nothing left to take away.\n - Antoine de Saint-Exupéry",
 "C is quirky, flawed, and an enormous success. - Dennis M. Ritchie.",
 "In theory, theory and practice are the same. In practice, they're not. - Yoggi Berra",
 "You can't have great software without a great team, and most software teams behave like dysfunctional families.\n - Jim McCarthy",
 "PHP is a minor evil perpetrated and created by incompetent amateurs, whereas Perl is a great and insidious evil,\n perpetrated by skilled but perverted professionals. - Jon Ribbens",
 "Programming is like kicking yourself in the face, sooner or later your nose will bleed. - Kyle Woodbury",
 "Perl - The only language that looks the same before and after RSA encryption. - Keith Bostic",
 "It is easier to port a shell than a shell script. - Larry Wall",
 "Learning to program has no more to do with designing interactive software\n than learning to touch type has to do with writing poetry - Ted Nelson",
 "The best programmers are not marginally better than merely good ones.\n They are an order-of-magnitude better, measured by whatever standard:\n conceptual creativity, speed, ingenuity of design, or problem-solving ability.\n - Randall E. Stross",
 "If McDonalds were run like a software company,\n one out of every hundred Big Macs would give you food poisoning,\n and the response would be,\n 'We're sorry, here's a coupon for two more.'\n - Mark Minasi",
 "Beware of bugs in the above code; I have only proved it correct, not tried it. - Donald E. Knuth.",
 "Computer system analysis is like child-rearing; you can do grievous damage, but you cannot ensure success.\n - Tom DeMarco",
 "I don't care if it works on your machine! We are not shipping your machine! - Vidiu Platon.",
 "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.\n - Christopher Thompson",
 "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.\n - Bill Gates",
 "Debugging is twice as hard as writing the code in the first place.\n Therefore, if you write the code as cleverly as possible,\n you are, by definition, not smart enough to debug it. - Brian W. Kernighan.",
 "People think that computer science is the art of geniuses\n but the actual reality is the opposite, just many people doing things that build on each other,\n like a wall of mini stones. - Donald Knuth",
 "First learn computer science and all the theory.\n Next develop a programming style.\n Then forget all that and just hack.\n - George Carrette",
 "Most of you are familiar with the virtues of a programmer.\n There are three, of course: laziness, impatience, and hubris.\n - Larry Wall",
 "Most software today is very much like an Egyptian pyramid with millions of bricks piled on top of each other,\n with no structural integrity, but just done by brute force and thousands of slaves.\n - Alan Kay",
 "The trouble with programmers is that you can never tell what a programmer is doing until it's too late. - Seymour Cray",
 "To iterate is human, to recurse divine. - L. Peter Deutsch",
 "On two occasions I have been asked [by members of Parliament]:\n 'Pray, Mr. Babbage, if you put into the machine wrong figures, will the right answers come out?'\n I am not able rightly to apprehend the kind of confusion of ideas that could provoke such a question.\n - Charles Babbage",
 "Most good programmers do programming not because they expect to get paid\n or get adulation by the public, but because it is fun to program. - Linus Torvalds",
 "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. - Martin Golding",
 "There are two ways of constructing a software design.\n One way is to make it so simple that there are obviously no deficiencies.\n And the other way is to make it so complicated that there are no obvious deficiencies.\n - C.A.R. Hoare",
 "Some things Man was never meant to know. For everything else, there's Google.",
"Failure is not an option -- it comes bundled with Windows.",
"Computer games don't affect kids; I mean if Pac-Man affected us as kids,\n we'd all be running around in darkened rooms, munching magic pills\n and listening to repetitive electronic music.",
"Artificial Intelligence usually beats natural stupidity.",
"To err is human... to really foul up requires the root password.",
"Like car accidents, most hardware problems are due to driver error.",
"If at first you don't succeed; call it version 1.0",
"If Python is executable pseudocode, then perl is executable line noise.",
"Programmers are tools for converting caffeine into code.",
"Why do we want intelligent terminals when there are so many stupid users?",
"I can't uninstall it, there seems to be some kind of 'Uninstall Shield'.",
"See daddy ? All the keys are in alphabetical order now.",
"Hey! It compiles! Ship it!",
"SUPERCOMPUTER: what it sounded like before you bought it.",
"Windows Vista: It's like upgrading from Bill Clinton to George W. Bush.",
"The more I C, the less I see.",
"Life would be so much easier if we only had the source code.",
"My software never has bugs. It just develops random features.",
"The only problem with troubleshooting is that sometimes trouble shoots back.",
"Crap... Someone knocked over my recycle bin... There's icons all over my desktop...",
"Relax, its only ONES and ZEROS !",
"rm -rf /bin/laden",
"The great thing about Object Oriented code is that it can make small, simple problems look like large, complex ones.",
"If brute force doesn't solve your problems, then you aren't using enough.",
"Unix is user-friendly. It's just very selective about who its friends are.",
 "Microsoft: You've got questions. We've got dancing paperclips.",
"I'm not anti-social; I'm just not user friendly",
"The world is coming to an end... SAVE YOUR BUFFERS !",
"If you don't want to be replaced by a computer, don't act like one.",
"Better to be a geek than an idiot.",
"I went to a gentleman's cybercafe -- and they offered me a 'laptop dance'.",
"After Perl everything else is just assembly language.",
"The Internet: where men are men, women are men, and children are FBI agents.",
"There are 10 types of people in the world: those who understand binary, and those who don't.",
"Difference between a virus and windows ? Viruses rarely fail.",
"Helpdesk: There is an icon on your computer labeled \"My Computer\".\n Double click on it.\n User: What's your computer doing on mine?",
"I think Microsoft named .Net so it wouldn't show up in a Unix directory listing.",
"If debugging is the process of removing bugs, then programming must be the process of putting them in.",
"Computer dating is fine, if you're a computer.",
"Any fool can use a computer. Many do.",
"Hardware: The parts of a computer system that can be kicked.",
"Those who can't write programs, write help files.",
"You know you're a geek when... You try to shoo a fly away from the monitor with your cursor. That just happened to me. It was scary.",
"Computer language design is just like a stroll in the park. Jurassic Park, that is.",
};
